apiVersion: apps/v1
kind: Deployment
metadata:
  name: couriers-service
  labels:
    app: couriers-service
spec:
  selector:
    matchLabels:
      app: couriers-service
  template:
    metadata:
      labels:
        app: couriers-service
    spec:
      containers:
        - name: couriers-service
          image: parcel-delivery-app/couriers-service:1.0.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: urls
            - configMapRef:
                name: postgres
            - secretRef:
                name: postgres
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
