apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init.sql: |
    CREATE SCHEMA IF NOT EXISTS "order";
    CREATE SCHEMA IF NOT EXISTS "courier";
    CREATE SCHEMA IF NOT EXISTS "uaa";